version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test