version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  pg:
    docker:
      - image: cimg/openjdk:11.0.17
        environment:
          DB_USER: pg
          DB_PASSWORD: 123
          DB_NAME: testdb
          DB_URL: jdbc:postgresql://localhost:5432/testdb
          COMMAND: updatesql
          PSQL_PAGER: ''
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: 123
    steps:
      - checkout
      - run: | 
          sudo apt update -y 
          sudo apt install postgresql-client
      - run: | 
          psql \
          -d postgres://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME \
          -c "\l"
      - run: unzip liquibase*.zip
      - run: |
          cd liquibase-spark-0.0.1-SNAPSHOT
          source ./scripts/sparkdb.sh uat updatesql

  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: Mvn verify and SonarCloud analysis
          command: mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=Sparks-Systems_sonarcloud-test
      - maven/process_test_results
      - store_artifacts:
          path: ./target/circleci-cicd.jar
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          checkout: false
          attach-workspace: true
          repo: $ECR_REPO

workflows:
  ci_pipeline:
    jobs:
      - pg
#       - build_and_test
#       - build_docker_img:
#           requires:
#             - build_and_test
