version: 2.1

orbs:
  maven: circleci/maven@1.4.0

jobs:
  build_test:
    executor: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn clean verify
      - maven/process_test_results
      - run: docker version

workflows:
  build_and_test:
    jobs:
      - build_test

