version: 2.1

orbs:
  maven: circleci/maven@1.4.0

jobs:
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn clean verify
      - maven/process_test_results
      - run: pwd
      - run: ls -lrt
      - run: ls target
      - persist_to_workspace:
          root: ./target
          paths: 
            - "*.jar"
  


workflows:
  ci_pipeline:
    jobs:
      - build_and_test
      # - docker_build:
      #     requires:
      #       - build_and_test

