version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  pg:
    docker:
      - image: cimg/python:3.10
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: circle_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: db_test
    steps:
      - checkout      
#       - run:
#           name: Install JDK and Maven
#           command: sudo apt update -y && sudo apt install default-jdk && sudo apt install maven
#       - run: mvn clean verify
      - run: sudo apt install postgresql-client
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: psql -d postgres://$POSTGRES_USER@localhost:5432/$POSTGRES_DB

  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: Mvn verify and SonarCloud analysis
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=Sparks-Systems_sonarcloud-test
      - maven/process_test_results
      - store_artifacts:
          path: ./target/circleci-cicd.jar
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          checkout: false
          attach-workspace: true
          repo: $ECR_REPO

workflows:
  ci_pipeline:
    jobs:
      - pg
#       - build_and_test
#       - build_docker_img:
#           requires:
#             - build_and_test
