version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - run: mvn clean verify
      - maven/process_test_results
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: docker/machine
    steps:
      - attach_workspace:
          at: ./
      - docker/build:
          image: circleci-img
          checkout: false
          
  build_docker_img_test:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ./
      - aws-ecr/build-and-push-image:
          repo: $ECR_REPO 

workflows:
  ci_pipeline:
    jobs:
      - build_and_test
      - build_docker_img_test:
          requires:
            - build_and_test
        

