version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_and_test:
    executor: maven/default
    working_directory: /tmp/wd
    steps:
      - checkout
      - run: mvn clean verify
      - maven/process_test_results
      - run: pwd
      - run: ls target
      - store_artifacts:
          path: /tmp/wd/target/circleci-cicd.jar
          destination: artifact-file
      - persist_to_workspace:
          root: /tmp/wd/
          paths: 
            - target/*.jar
            - Dockerfile
      
          
  build_docker_img:
    executor: aws-ecr/default
    working_directory: /tmp/wd
    steps:
      - aws-ecr/build-and-push-image:
          checkout: false
          attach-workspace: true
          repo: $ECR_REPO # env variable

workflows:
  ci_pipeline:
    jobs:
      - build_and_test
      - build_docker_img:
          requires:
            - build_and_test