version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn clean verify
      - maven/process_test_results
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: docker/default
    steps:
      - attach_workspace:
          at: ./
      - docker/build:
          name: circleci-project

workflows:
  ci_pipeline:
    jobs:
      - build_and_test
      - build_docker_img:
          requires:
            - build_and_test

