version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  aws-ecr: circleci/aws-ecr@8.2.1
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  code_scan:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: SonarCloud Analysis
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=Sparks-Systems_sonarcloud-test
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - run: mvn clean verify
      - maven/process_test_results
      - store_artifacts:
          path: ./target/circleci-cicd.jar
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          checkout: false
          attach-workspace: true
          repo: $ECR_REPO

workflows:
  ci_pipeline:
    jobs:
      - code_scan
      - build_and_test
      - build_docker_img:
          requires:
            - build_and_test
