version: 2.1

orbs:
  maven: circleci/maven@1.4.0

# workflows:
#   maven_test:
#     jobs:
#       - maven/test 

jobs:
  build:
    machine: true
    steps:
      - maven/with_cache:
        steps:
          - run: echo "The dependencies are installed"

workflows:
  maven_test:
    jobs:
      - build

