version: 2.1

orbs:
  maven: circleci/maven@1.4.0

jobs:
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn clean verify
      - maven/process_test_results
      - persist_to_workspace:
          root: ./target
          paths: 
            - "*.jar"
            - Dockerfile

  docker_build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./
      - run: ls -lrt
      # - run: docker build -t circleci-cicd .
  

workflows:
  ci_pipeline:
    jobs:
      - build_and_test
      - docker_build:
          requires:
            - build_and_test

