version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
  pg:
    docker:
      - image: cimg/postgres:15.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: apt install postgresql-client
      - run:
          name: Install JDK and Maven
          command: apt update -y && apt install default-jdk && apt install maven
      - run: mvn clean verify
  build_and_test:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: Mvn verify and SonarCloud analysis
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=Sparks-Systems_sonarcloud-test
      - maven/process_test_results
      - store_artifacts:
          path: ./target/circleci-cicd.jar
      - persist_to_workspace:
          root: ./
          paths: 
            - target/*.jar
            - Dockerfile

  build_docker_img:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          checkout: false
          attach-workspace: true
          repo: $ECR_REPO

workflows:
  ci_pipeline:
    jobs:
      - build
      - build_and_test
      - build_docker_img:
          requires:
            - build_and_test
